# 1. Datos principales de conexión (Usuario y clave: postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=prueba
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate para el esquema
spring.jpa.properties.hibernate.default_schema=prueba
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Estrategia de creación de tablas
# 'update' creará o modificará las tablas en tu esquema automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update

# 4. Logs de SQL en consola (Útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mi_clave_secreta_super_segura_para_logitrack_2026
jwt.expiration=86400000